### ISSUE TITLE
Memory leak in SMS.f19_g16.X.hobart_intel

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cmeps-cime#37]
Running for 5 days I see about 1GB per task, 
running for 10 days I see 1.4 GB per task.

**Comment by jedwards4b** [comment]
It appears that the problem is in variables FBNormSrc and FBNormDst in subroutine med_map_Regrid_Norm.  These variables are created multiple times and never cleaned.

**Comment by mvertens** [comment]
@jedwards4b - great catch! Glad its not internal to ESMF. Thanks for
tracking this down.
