### ISSUE TITLE
problems using pio2 or pio1 with pnetcdf 

### ISSUE THREAD

**Issue by mvertens** [ESMCI/cmeps-cime#78]
I am running the following compset:
`SMS_Vnuopc_Ln5.f45_f45_mg37.I2000Clm50SpNuopc.cheyenne_intel.clm-nuopc_cap`
in my work to introduce an ungridded time dimension in the import/export fields.

If I use PIO2 with pnetcdf, the time variable in the clm history file is garbage.
If I use PIO1 with pnetcdf, I get a crash in DUSTMod with the following traceback
```
0:cesm.exe           0000000000AA28FF  abortutils_mp_end          50  abortutils.F90
0:cesm.exe           00000000006FF6AF  dustmod_mp_dustem         336  DUSTMod.F90
0:cesm.exe           00000000004D6D75  clm_driver_mp_clm         670  clm_driver.F90
0:cesm.exe           00000000004BC01B  lnd_comp_nuopc_mp         823  lnd_comp_nuopc.F90
```
With netcdf and PIO1 - everything runs fine. 

In addition, if I compare the times using PIO2 versus PIO1,
The LND Run Time with PIO2 is 2.390 seconds
The LND Run Time with PIO1 is .909 seconds

**Comment by jedwards4b** [comment]
Please provide the information necessary to reproduce the problem.  Can I do this on the current nuopc-cmeps head?

**Comment by mvertens** [comment]
@jedwards4b - please try at the head of nuopc-cmeps - or use my sandbox
at ~/src/UFSCOMP.jan19. You can definitely reproduce this if you create the
test from my sandbox - and I assume that it also holds at the head of
nuopc-cmeps with the appropriate externals for the prognostic components.

**Comment by jedwards4b** [comment]
On the head of nuopc-cmeps 
```
PASS SMS_Vnuopc_Ln5.f45_f45_mg37.I2000Clm50SpNuopc.cheyenne_intel.clm-nuopc_cap CREATE_NEWCASE
PASS SMS_Vnuopc_Ln5.f45_f45_mg37.I2000Clm50SpNuopc.cheyenne_intel.clm-nuopc_cap XML
PASS SMS_Vnuopc_Ln5.f45_f45_mg37.I2000Clm50SpNuopc.cheyenne_intel.clm-nuopc_cap SETUP
PASS SMS_Vnuopc_Ln5.f45_f45_mg37.I2000Clm50SpNuopc.cheyenne_intel.clm-nuopc_cap SHAREDLIB_BUILD time=270
PASS SMS_Vnuopc_Ln5.f45_f45_mg37.I2000Clm50SpNuopc.cheyenne_intel.clm-nuopc_cap MODEL_BUILD time=54
PASS SMS_Vnuopc_Ln5.f45_f45_mg37.I2000Clm50SpNuopc.cheyenne_intel.clm-nuopc_cap SUBMIT
PASS SMS_Vnuopc_Ln5.f45_f45_mg37.I2000Clm50SpNuopc.cheyenne_intel.clm-nuopc_cap RUN time=30
PASS SMS_Vnuopc_Ln5.f45_f45_mg37.I2000Clm50SpNuopc.cheyenne_intel.clm-nuopc_cap MEMLEAK insuffiencient data for memleak test
PASS SMS_Vnuopc_Ln5.f45_f45_mg37.I2000Clm50SpNuopc.cheyenne_intel.clm-nuopc_cap SHORT_TERM_ARCHIVER
```

**Comment by jedwards4b** [comment]
I also ran from ~mvertens/src/UFSCOMP.jan19/cime/scripts/
cheyenne3: /glade/u/home/mvertens/src/UFSCOMP.jan19/cime/scripts
:) qcmd -- ./create_test SMS_Vnuopc_Ln5.f45_f45_mg37.I2000Clm50SpNuopc.cheyenne_intel.clm-nuopc_cap
```
PASS SMS_Vnuopc_Ln5.f45_f45_mg37.I2000Clm50SpNuopc.cheyenne_intel.clm-nuopc_cap CREATE_NEWCASE
PASS SMS_Vnuopc_Ln5.f45_f45_mg37.I2000Clm50SpNuopc.cheyenne_intel.clm-nuopc_cap XML
PASS SMS_Vnuopc_Ln5.f45_f45_mg37.I2000Clm50SpNuopc.cheyenne_intel.clm-nuopc_cap SETUP
PASS SMS_Vnuopc_Ln5.f45_f45_mg37.I2000Clm50SpNuopc.cheyenne_intel.clm-nuopc_cap SHAREDLIB_BUILD time=260
PASS SMS_Vnuopc_Ln5.f45_f45_mg37.I2000Clm50SpNuopc.cheyenne_intel.clm-nuopc_cap MODEL_BUILD time=56
PASS SMS_Vnuopc_Ln5.f45_f45_mg37.I2000Clm50SpNuopc.cheyenne_intel.clm-nuopc_cap SUBMIT
PASS SMS_Vnuopc_Ln5.f45_f45_mg37.I2000Clm50SpNuopc.cheyenne_intel.clm-nuopc_cap RUN time=19
PASS SMS_Vnuopc_Ln5.f45_f45_mg37.I2000Clm50SpNuopc.cheyenne_intel.clm-nuopc_cap MEMLEAK insuffiencient data for memleak test
PASS SMS_Vnuopc_Ln5.f45_f45_mg37.I2000Clm50SpNuopc.cheyenne_intel.clm-nuopc_cap SHORT_TERM_ARCHIVER
```

**Comment by jedwards4b** [comment]
I've pushed a fix to:
To https://github.com/mvertens/ctsm.git
   eb07bf2..8ab1d37  mvertens/nuopc_cap -> mvertens/nuopc_cap

this also fixes an issue with flds_scalar in debug mode
